### ISSUE TITLE
API design: general

### ISSUE THREAD

**Issue by blootsvoets** [RADAR-CNS/ManagementPortal#87] opened 2017-10-05 10:56 UTC
Related to #81, there are a number of entities in the API that have a human-readable identifier. From an API point of view, its nicer to expose in paths than to use an internal ID. Alternatively, both the human readable and the internal ID could be exposed using different paths, but that would increase the maintenance overhead. Possible mappings:

User/subject -> `login`
Source -> `sourceName`
DeviceType -> `deviceProducer/deviceType/catalogVersion`
Project -> `projectName`
Role -> is a tough one, perhaps ID is the only good mapping. It might also be `projectName/login/authority` though
SourceData (DeviceTypeData?) -> `deviceProducer/deviceType/catalogVersion/topic`

This would be a major overhaul, but it would improve the readability of requests. An index on the respective properties would also help. Please comment @dennyverbeeck @nivemaham.

**Comment by dennyverbeeck** [comment] 2017-10-12 15:41
I think it makes a lot of sense. I'll make this my priority, so it can be included in the 0.1 release and consumers of our API have time to adapt their code as well.

**Comment by dennyverbeeck** [comment] 2017-10-17 08:55
I have implemented the changes and will wait for the merge of #93, so i can rebase and check for conflicts. 

- `User` and `Subject` were already referenced by `login`
- Changed `Source`, `DeviceType` and `Project` according to the suggestions
- `Role` is now referenced by `projectName/authorityName` e.g. `GET /api/roles/project-1/PROJECT_ADMIN`
- `SourceData`: no change yet

I'm not sure if we can guarantee `deviceProducer/deviceType/catalogVersion/topic` to be unique, in the current data model, a `DeviceType` can have multiple `SourceData`s that would write to the same topic. Perhaps it would be better to make the `sensorName` field unique and use that? Multiple `SensorData`s with the same name might cause confusion anyway. What do you think @blootsvoets @nivemaham ?

**Comment by dennyverbeeck** [comment] 2017-10-23 12:32
Will go ahead with using `sensorName` for `SensorData`, we can discuss when everyone is back from vacation. If necessary we can always revert the commit for the `sensor-data` api only and implement another strategy.

**Comment by nivemaham** [comment] 2017-11-20 10:34
I am reopening this issue, following the discussion here and #101 . As we have already mentioned that the `api/source-data/sensorName` is not valid since we can have the same sensor in multiple source-types. Specially, this is the case when we want to auto import the source-type definitions from source-catalog server . As i am working on that, we need to finalize this API too. The property names are synchronized with the response from catalogs as much as possible to have a general understanding across the platform. 
I will rename `sensorName` to `sensorType` or `sourceDataType`. Please give any suggestions if there is any  other better name. The response from catalog server response has a property named as `type` to denote this. 
We have two suggestions.
1. Use `GET /api/sensor-data/<source-producer>/<source-type>/<catalog-version>/<sensor-name>`
2. Use the numeric id as `GET /api/source-data/id`.

I think both should work. However, for now i don't see enough information for `active-source-types` in the catalog for `producer/model/version` fields. I think the numberic id would make life a lot easier for implementation. But less straight forward for the end-users of the api. so i propose we can have the apis for `source-data` as `source-data/id` and add an api in `source-type` to expose the `source-data`s assigned in that particular `source-type` as `api/source-type/<producer>/<model>/<version>/source-data`. 

What is your opinion? @dennyverbeeck @blootsvoets

**Comment by dennyverbeeck** [comment] 2017-11-20 11:34
Ok, i agree with `sourceDataType` to match the `type` property from the catalog.

So i think the idea was to add a `type` field rather than to rename `name` to `type`, to address that we have similar sensors in multiple sources. This allows us to define different types of e.g. accelerometers. Then we can keep the `name` field to just have a human readable unique identifier which could be something like `Empatica-E4-Accelerometer`, which can also be used in the API to uniquely address an entity. This addresses the issue of our API becoming too verbose, and addresses the issue of still allowing to group different sensors of the same type together. (For future reference, the discussion was [here](https://github.com/RADAR-CNS/ManagementPortal/pull/101#commitcomment-25355763).)

Using option 2 presented above would be fine as well but i think less preferable. Our other entities are identified by human-readable identifiers so this would make the whole API consistent. Also having a database ID as API identifier opens one up to enumeration attacks, although this is probably not an issue since the soureData is not sensitive information.

As for the name of the type field i think `sourceDataType` is a good name that follows other conventions.

**Comment by dennyverbeeck** [comment] 2017-11-20 11:40
Also, is a `SourceData` supposed to be a component of a specific `SourceType`? Because in the current datamodel `SourceData` - `SourceType` is many-to-many, if a `SourceData` is specific to a `SourceType` it should be many-to-one.

**Comment by blootsvoets** [comment] 2017-11-20 11:40
For uniqueness, the catalog version also needs to be in the source data `name`. If the `name` property is absent, perhaps it can be autogenerated from `deviceProducer`, `deviceModel`, `catalogVersion` and `type` (plus, if there are duplicates in type, add an index?) Otherwise uniqueness will be hard to maintain.

**Comment by blootsvoets** [comment] 2017-11-20 11:41
It probably should be many to one then.

**Comment by nivemaham** [comment] 2017-11-20 17:10
Yes. ManyToOne it is. ManyToMany was designed based on very old ideas.

**Comment by dennyverbeeck** [comment] 2017-11-21 20:21
I think with the merge of PR's #134 and #138 we can close this again.

**Comment by nivemaham** [comment] 2017-11-22 16:05
I agree.

**Closed** 2017-11-23 08:57 UTC
